[RAP] fixed build.properties files for Tomcat deployment
Some directories and files were not in the binary build path and therefore not added to the war deployment. This should fix the NoClassDefFoundError Exceptions in tomcat server.